# Generated by Django 3.0 on 2020-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(default='', upload_to='Shop/product_image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
